# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6040f83b2b1a1fbd97e23ff80bc6be7b7c80444d39d363a2f6b2c97799aed80c80f8a9fe2dfa205638d4bd4d341f95b2f935d84979799c604f0c5a84ddc2f3a5

test:
  secret_key_base: 9657c0e3186ca59dc703014acb62b82ab74ade1721adec72815550a06437fd53290fa84e198bebb0e3ea4daaef8e9c04854ca2d2a6095fd338848fbfc7eaaeac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
